# Generated by Django 5.0.4 on 2025-09-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedpost',
            name='content_mac',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='encryptedpost',
            name='title_mac',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
