# Generated by Django 5.0.6 on 2025-09-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_encryptedpost_content_mac_encryptedpost_title_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedpost',
            name='content_mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedpost',
            name='title_mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
