# Generated by Django 5.0.6 on 2025-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_encryptedpost_content_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
